### PR TITLE
Replaced BrandingValueResolver with RootContentResolver.

### PR DESCRIPTION
**Pull request by leekelleher**
The reason for this is that the `BrandingValueResolver` would get the Root content node, then manually map it to the `Branding` property.

Whereas we can leverage Ditto to do this automatically.  If we return the Root content node from the value-resolver, then Ditto will know that an `IPublishedContent` is being returned
and will attempt to map it to the target type, (in this case the `Branding` object).

We could have kept the `BrandingValueResolver` class name and returned this...

```
return ContentResolver.Instance.GetRootContent().As<Branding>();
```

But I thought if we changed it to only return the Root content node, then it could potentially be reused.

### CODE REVIEW

**Comment by leekelleher** [comment]
Let me know if this needs further explanation.

**Comment by BarryFogarty** [comment]
Good idea - so from what you said above, `Branding` properties will map automatically once the resolver returns the right `IPublishedContent`?

**Comment by leekelleher** [comment]
Correct! :+1: 

Think of it like this...

``` csharp
[DittoValueResolver(typeof(RootContentResolver))]
public Branding Branding { get; set; }
```

...equals...

``` csharp
ContentResolver.Instance.GetRootContent().As<Branding>();
```

**Comment by BarryFogarty** [comment]
Awesome.  Makes a lot of sense.  I think this can be applied to a few other areas.

**Pull request merged**
