### PR TITLE
Renamed BasketLinkResolver to BasketContentResolver.

### PR DESCRIPTION
**Pull request by leekelleher**
Similar to PR #3, the `BasketLinkResolver` was manually creating and mapping the Basket node to a `Link` object-type.

If we return the `IPublishedContent` for the Basket node, then we can let Ditto handle the mapping.

### CODE REVIEW

**Comment by BarryFogarty** [comment]
@leekelleher can you see if you can resolve the conflicts with the base branch and update the PR please?  Might be to do with a previous PR merge.

**Comment by leekelleher** [comment]
Sure thing, I'll rebase and update.

**Comment by leekelleher** [comment]
@BarryFogarty All up to date now.

**Comment by BarryFogarty** [comment]
awesome work sir :+1: #H5YR

**Comment by leekelleher** [comment]
No worries at all!

I'm out of time this morning, gotta get back to the grind :shipit:

**Pull request merged**
